baseURL = "https://dpavle.me/"
defaultContentLanguage = "en"
languageCode = "en"

title = "Pavle Dencic"

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/dpavle/dpavle.me-hugo"
    weight = 3
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"

[params]
  avatarURL = "/images/avatar.png"
  description = "Aspiring DevOps Engineer / Sysadmin"

  accentColor = "#4ca6c9"

  footer = "- hosted on Amazon AWS with NGINX"

  socialIcons = [
    {name = "github", url = "https://github.com/dpavle"},
    {name = "email", url = "mailto:dencic.pavle@gmail.com"},
    {name = "linkedin", url = "https://www.linkedin.com/in/pavle-den%C4%8Di%C4%87-a4ba26179/"},
  ]